### ISSUE TITLE
Virtual Camera Not showing up in PeerConnectionClient

### ISSUE THREAD

**Issue by DanielRourke** [webrtc-uwp/webrtc-uwp-sdk#106]
Hello i am trying to use OBS virtual camera as a input to PeerConnectionClient but it does not appear in the drop down for Cameras. Any suggestions on achieving this?

**Comment by jamescadd** [comment]
This is due to Media Foundation not support virtual devices like Direct Show does today.  I do think it would be a good feature to add but don't have a solution currently.  If you want to try implementing this yourself you might start by looking at the current video capture component: https://github.com/webrtc-uwp/webrtc-apis/blob/master/windows/wrapper/impl_webrtc_VideoCapturer.cpp

**Comment by DanielRourke** [comment]
Thanks for the clarification. I will try a different approach.
