### ISSUE TITLE
Org.WebRtc.winmd and ChatterBox.Background.winmd is missing while building ChatterBox sample 

### ISSUE THREAD

**Issue by saschenjka** [webrtc-uwp/webrtc-uwp-sdk#25]
I have Visual Studio 2017 15.4.1 and I prepared webrtc with prepare.bat, then I built WebRtc.sln. It was OK. Now I try to build ChatterBox example and have following errors.

German Visual Studio 2017 error outputs with translation in brackets:

> Fehler (Error)	CS0006	Metadatendatei "C:\webrtc-uwp-sdk\common\windows\samples\ChatterBox\Build\Output\x86\Debug\Org.WebRtc\Org.WebRtc.winmd" wurde nicht gefunden. (was not found)

> Fehler (Error)	CS0006	Metadatendatei "C:\webrtc-uwp-sdk\common\windows\samples\ChatterBox\Output\ChatterBox.Background\bin\ARM\Debug\ChatterBox.Background.winmd" wurde nicht gefunden. (was not found)

**Comment by travelhawk** [comment]
The same for me happens when I try to build the sample PeerCC.

**Comment by jamescadd** [comment]
@vmancic could you take a look?

**Comment by vmancic** [comment]
issue reproduced on master branch, working on fix.

**Comment by travelhawk** [comment]
Is there any update on this?

**Comment by vmancic** [comment]
Sorry, no updates yet. I worked on other tasks, but this is first on my list when I finish my current task.

**Comment by vmancic** [comment]
some more details can be found here: 

https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/23#event-1430417639

**Comment by jamescadd** [comment]
@saschenjka would this version of Chatterbox be sufficient for you? https://github.com/webrtc-uwp/ChatterBox-Sample  It builds against a previous version of the NuGet package and still compiles/runs as-is.  We stopped active development on Chatterbox due to the Windows VoIP implementation currently requiring a 2 process model which forced an implementation that caused poor performance on HoloLens.  The sample is available as a reference for implementing VoIP apps, but PeerConnection is the preferred (and more performant) sample.

Could you let us know if you need a Chatterbox sample with full source available, or if the NuGet version referenced above is enough?

**Comment by jamescadd** [comment]
Deprecating the full-source Chatterbox repro and referring to Chatterbox-Sample in documentation.  Replaced by: https://github.com/webrtc-uwp/ChatterBox-Sample
