### ISSUE TITLE
mismatch between compiler and library versions when building solution

### ISSUE THREAD

**Issue by HenryCui1979** [webrtc-uwp/webrtc-uwp-sdk#3]
I built the solution,and only built some projects successfully,but others failed.The error ouputed as follow:'EventRegistrationToken': identifier not found - possible mismatch between compiler and library versions. Please ensure vccorlib.h/.lib, vccorlib120.dll and c1xx.dll match.What should I do to resolve this issue?

**Comment by LaurianeC** [comment]
Have you solved this ? Would be interested in knowing how.

**Comment by viprinrin00** [comment]
I got the same issue with you guys.
Found something [https://stackoverflow.com/questions/35097929/cl-exe-mismatch-between-compiler-and-library-versions-when-building-universal-ap](here) on Stackoverflow
Fixed by running vcvarsall.bat at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC with options.
The solution's quite clear but the script turn off echo `@Echo off`. I might input wrong arguments and did not fix anything.
Hope it help. If it works, please tell me how you do this

**Comment by LaurianeC** [comment]
I solved this by setting Target Platform Version to v10586 in my Visual Studio project parameters.

**Comment by HenryCui1979** [comment]
I use perl(command line) to create the solution follow the guide,than it successed.
