### ISSUE TITLE
Forcing the metal view to draw inside layout guide

### ISSUE THREAD

**Issue by jamescadd** [webrtc-uwp/webrtc-uwp-sdk#38]
@markcdb commented on [Tue Feb 27 2018](https://github.com/webrtc-uwp/webrtc/issues/3)

https://github.com/webrtc-uwp/webrtc/blob/6661764acc8a6d60d8d9e950c049cc67822bf902/sdk/objc/Framework/Classes/Metal/RTCMTLVideoView.m#L95

the clipping for this constraint is causing the view to render inside container's view layout guide even when not necessary

---

@jamescadd commented on [Thu Mar 01 2018](https://github.com/webrtc-uwp/webrtc/issues/3#issuecomment-369729059)

@morosev could you take a look and see if we should adjust?

**Comment by morosev** [comment]
I'm not sure about iOS support, but the owner of that code is Google. It could be seen that that part of code has been changed since M62 webrtc release. We will take the recent changes in our next merger.
Latest file version: https://chromium.googlesource.com/external/webrtc/+/master/sdk/objc/Framework/Classes/Metal/RTCMTLVideoView.m
M62 version from original source: https://chromium.googlesource.com/external/webrtc/+/bb547203bfebcc478b263c4e9ca173c6fd5a0c5d/sdk/objc/Framework/Classes/Metal/RTCMTLVideoView.m
